### ISSUE TITLE
[ISSUE] Doesn't work 

### ISSUE THREAD

**Issue by AdaelynXIV** [Retr0-01/CSGO-Discord-RP#3]
**Describe the issue**
I launch the exe, the console says it's listening to data on the right port but there's nothing displaying on Discord from the app.

**Desktop (please complete the following information):**
- OS: Windows 11
- Version: v2.0
- Game Version: Latest 10/10 update.

**Comment by Retr0-01** [comment]
Since the app launches normally and it's also listening to data, is there a chance you have set your Discord client to not show your current activity?

Go into ``Discord -> Settings -> Activity Privacy`` and see whether the first option is disabled or not.
![image](https://github.com/Retr0-01/CS2-Discord-RP/assets/61121754/f311f6b9-7451-4495-b96b-93aea4b2ab43)

**Comment by AdaelynXIV** [comment]
I have it on, yes!

**Comment by Retr0-01** [comment]
Hello,

I apologize for the delay. I will have any issues related to this app fixed by the end of the next week. I am on a pretty tight schedule right now so I cannot look at it immediately.

Thanks.

**Comment by Retr0-01** [comment]
Because of how little info this issue provides, I would recommend downloading the [latest version](https://github.com/Retr0-01/CS2-Discord-RP/releases/latest) of the app which has been updated and try launching it again.

I will close this now. Feel free to re-open it if you encounter any issues.
